### ISSUE TITLE
Syntax problem

### ISSUE THREAD

**Issue by robinwayne** [padok-team/terraform-google-network#10]
https://github.com/padok-team/terraform-google-network/blob/959124088a4a1586ecadc077b04178f4033b8d73/variables.tf#L69

Could you please remove the dot in order to have  "ERRORS_ONLY" ? I got the following error using your module 
Error: expected log_config.0.filter to be one of [ERRORS_ONLY TRANSLATIONS_ONLY ALL], got ERRORS_ONLY.

Thanks !

**Comment by JulienJourdain** [comment]
As you're a owner, could you please review my PR 🙏 
https://github.com/padok-team/terraform-google-network/pull/11
