### ISSUE TITLE
Feature request: enable Compute Engine API within module

### ISSUE THREAD

**Issue by busser** [padok-team/terraform-google-network#20]
Applying this module on a freshly created Google project fails because the Compute Engine API is disabled.

Could we enable the API from within the module? It would look something like this:

```terraform
resource "google_project_service" "compute_engine" {
  service            = "compute.googleapis.com"
  disable_on_destroy = false
}
```

Or, alternatively, could we add the activation of the API to the module's examples as a dependency?

**Comment by Alan-pad** [comment]
I don't think we want the enablement of APIs in this module. I would suggest using this module : https://github.com/terraform-google-modules/terraform-google-project-factory for bootstrapping projects and activating its APIs.

**Comment by Alan-pad** [comment]
However I think listing APIs the module depends on should be included in the README.md of each google module @padok-team/library-gcp WDYT ?

**Comment by busser** [comment]
Agreed. For future reference, two APIs need to be enabled:
- compute.googleapis.com
- servicenetworking.googleapis.com

**Comment by JulienJourdain** [comment]
👋 Agree with you!
I do not think that we should enable APIs in this module. However, we could update the README.md and examples to indicate that there is a dependency with the `servicenetworking` and `compute` APIs.
